# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/focal64"
  
  # VM config.
  config.vm.provider :virtualbox do |v|
    v.name = "ubuntu20.test"
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    # web.vm.synced_folder ".", "/vagrant", disabled: true
  end

  # Network settings.
  config.vm.network :private_network, ip: "192.168.30.30"
  config.vm.hostname = "ubuntu20.test"
  
  # Provisioning.
  config.vm.provision :shell, path: "bootstrap.sh"
end
